# Generated by Django 5.0.4 on 2024-04-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Chats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pregunta", models.TextField()),
                ("respuesta", models.TextField()),
                ("valoracion", models.BooleanField(blank=True)),
                ("comentario_val", models.CharField(max_length=250)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "id_conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_sarebot.conversacion",
                    ),
                ),
            ],
        ),
    ]
