# Generated by Django 5.0.4 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
