# Generated by Django 5.0.4 on 2024-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sarebot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="comentario_val",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
