# Generated by Django 5.0.4 on 2024-04-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Registro',
        ),
    ]
