# Generated by Django 5.0.4 on 2024-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0002_alter_chat_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
