# Generated by Django 5.0.4 on 2024-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0002_rename_chat_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='origen',
            field=models.CharField(default='Consulta', max_length=20),
            preserve_default=False,
        ),
    ]
