# Generated by Django 5.0.4 on 2024-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sarebot", "0002_alter_chats_comentario_val"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propmts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_prompt", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("texto", models.TextField()),
            ],
        ),
    ]
