# Generated by Django 5.0.4 on 2024-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0003_registro_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='valoracion',
            field=models.BooleanField(blank=True, choices=[(True, 'Buena'), (False, 'Mala')], null=True),
        ),
    ]
