# Generated by Django 5.0.4 on 2024-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0003_chat_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fichero', models.FileField(upload_to='data/')),
            ],
        ),
    ]
