# Generated by Django 5.0.4 on 2024-04-23 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_sarebot", "0003_propmts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propmts",
            old_name="nombre_prompt",
            new_name="nombre",
        ),
    ]
