# Generated by Django 5.0.4 on 2024-04-23 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_sarebot", "0004_rename_nombre_prompt_propmts_nombre"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chats",
            new_name="Chat",
        ),
        migrations.RenameModel(
            old_name="Propmts",
            new_name="Prompt",
        ),
    ]
