# Generated by Django 5.0.4 on 2024-04-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0005_rename_chats_chat_rename_propmts_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id_conversacion',
        ),
        migrations.AddField(
            model_name='chat',
            name='id_prompt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app_sarebot.prompt'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
    ]
