# Generated by Django 5.0.4 on 2024-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sarebot', '0006_remove_chat_id_conversacion_chat_id_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='comentario_val',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='valoracion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
